spring.application.name=my-market-app

server.port=8080

# ????????? ???? ??????
spring.r2dbc.url=r2dbc:h2:mem:///marketdb?options=DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.sql.init.mode=always
spring.r2dbc.initialization-mode=always

# ???????? Embedded Redis
app.redis.embedded=true

# Redis ????????? (??? Embedded)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000ms
spring.data.redis.connect-timeout=5000ms
spring.data.redis.client-type=lettuce

# Lettuce Client Configuration
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# ???????????
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=mymarket:

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ???????????
logging.level.ru.yandex.practicum.mymarket=DEBUG
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n